server:
  port: 10800
session:
  cookie:
    http-only: true
    name: "SESSION_TOKEN"
    path: "/"
    secure: true

spring:
  application:
    name: "web-client"
  thymeleaf:
    cache: false
    enabled: true
  data:
    redis:
      host: "localhost"
      port: 6379


services:
  auth-module: http://localhost:2228
  main-module: http://localhost:8082
