server:
  port: 10800

spring:
  application:
    name: "web-client"
  thymeleaf:
    cache: false
    enabled: true

services:
  auth-module: http://localhost:2228
  main-module: http://localhost:8082

